//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApp.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Log = new HashSet<Log>();
            this.Post = new HashSet<Post>();
        }
    
        public string ID { get; set; }
        [Required(ErrorMessage = "Thông tin bắt buộc")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Thông tin bắt buộc")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Thông tin bắt buộc")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Thông tin bắt buộc")]
        public string Fullname { get; set; }
        [Required(ErrorMessage = "Thông tin bắt buộc")]
        public byte Active { get; set; }
        public System.DateTime AccessDate { get; set; }
        [Required(ErrorMessage = "Thông tin bắt buộc")]
        public int Role_ID { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
    }
}
