//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApp.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string ID { get; set; }
        public string Content { get; set; }
        public System.DateTime PubDate { get; set; }
        public string AccountID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
